### ISSUE TITLE
How to setup s3 with minio

### ISSUE THREAD

**Issue by gribanoveu** [codex-team/codex.docs#317]
i use compose project like this:

```
s3:
    container_name: codex_minio
    image: minio/minio:latest
    restart: unless-stopped
    environment:
        MINIO_ROOT_USER: mini
        MINIO_ROOT_PASSWORD: mini
        MINIO_ACCESS_KEY: minio
        MINIO_SECRET_KEY: minio123
    ports:
        - 9000:9000
        - 9001:9001
    volumes:
        - minio:/data
    command: server /data --console-address ":9001"
```

and setting 

```
uploads:
  driver: "s3"
  s3:
    bucket: "codex"
    region: "eu-central-1"
    baseUrl: "http://localhost:9000"
    keyPrefix: "/"
    accessKeyId: "minio"
    secretAccessKey: "minio123"
```

but after i load file i see
```
2024-05-08 15:32:46 POST /api/transport/image 500 524.132 ms - 148
2024-05-08 15:32:46 PermanentRedirect: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.
2024-05-08 15:32:46     at throwDefaultError (/usr/src/app/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:8:22)
2024-05-08 15:32:46     at deserializeAws_restXmlPutObjectCommandError (/usr/src/app/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:5781:43)
2024-05-08 15:32:46     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2024-05-08 15:32:46     at async /usr/src/app/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
2024-05-08 15:32:46     at async /usr/src/app/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:13:20
2024-05-08 15:32:46     at async StandardRetryStrategy.retry (/usr/src/app/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
2024-05-08 15:32:46     at async /usr/src/app/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/flexibleChecksumsMiddleware.js:56:20
2024-05-08 15:32:46     at async /usr/src/app/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22
2024-05-08 15:32:46     at async Promise.all (index 0)
2024-05-08 15:32:46     at async Upload.__uploadUsingPut (/usr/src/app/node_modules/@aws-sdk/lib-storage/dist-cjs/Upload.js:66:26)
```

where i can get worked config?

**Comment by nikmel2803** [comment]
hey! sorry for the confusion, the `baseUrl` option is currently not used, so only AWS implementation is supported. pull requests are welcome!
